<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Rates.FinanceService.Application</RootNamespace>
    <AssemblyName>Rates.FinanceService.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="MediatR.Contracts" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Application\Rates.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Contracts\Rates.BuildingBlocks.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Domain\Rates.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\Rates.FinanceService.Domain\Rates.FinanceService.Domain.csproj" />
  </ItemGroup>

</Project>